/**
 * Comment anchors — the canvas renders *cues*, never comment content.
 *
 * The package has no idea what a comment says, who wrote it, or when. It knows
 * that a thread exists and where it is pinned, so it can draw a marker and tell
 * you when the user clicks one. Thread bodies, authorship, persistence and the
 * composer UI all live in the consuming webapp, the same way engine adaptation
 * does.
 */

/** Where a thread is pinned. */
export type CommentTarget =
  /** Free-form: pinned to a spot on the drawing, in image pixel coordinates. */
  | { kind: "point"; at: [number, number] }
  /** Attached: pinned to an annotation, and moves with it. */
  | { kind: "annotation"; annotationId: string };

/**
 * One thread's marker. Supply these through the `comments` prop — it is
 * display-only and fully controlled, so the canvas never mutates it.
 */
export interface CommentAnchor {
  /** Your thread id. Echoed back by `onCommentSelect` / `onCommentDelete`. */
  id: string;
  target: CommentTarget;
  /** Thread length. Rendered inside the marker when greater than 1. */
  count?: number;
  /** Resolved threads render dimmed, in the muted colour, but stay clickable. */
  resolved?: boolean;
  /** Passthrough — the package stores nothing and reads nothing from this. */
  meta?: Record<string, unknown>;
}

/**
 * Emitted when the user asks for a new thread. Nothing has been created yet:
 * open your composer, persist on submit, then push a `CommentAnchor` into the
 * `comments` prop.
 */
export interface CommentDraft {
  /**
   * A provisional id generated by the canvas. Adopt it as the thread id or
   * ignore it and use your own — the draft marker clears either way.
   */
  id: string;
  target: CommentTarget;
  /** What the user typed in the canvas comment box. Never empty. */
  text: string;
  /** Marker position in container-relative screen px, if you want to echo it. */
  screenPos: { x: number; y: number };
}

/**
 * An undo/redo step the canvas cannot perform itself.
 *
 * The canvas orders comment operations in the same history as annotation edits,
 * so Ctrl+Z always undoes the last thing the user did whichever kind it was. But
 * it never held the thread's content, so it cannot put a deleted thread back —
 * it tells you to, and you restore from your own soft-deleted copy.
 *
 * The two actions are exact inverses, which is what makes redo work: undoing a
 * delete is `restore`, redoing it is `remove`, and vice versa for a create.
 */
export interface CommentUndoOp {
  /** `restore` — put this thread back. `remove` — take it away again. */
  action: "restore" | "remove";
  /** The thread id, matching the `CommentAnchor.id` you supplied. */
  id: string;
  /**
   * The anchor as the canvas last knew it — present when restoring a thread the
   * canvas had rendered. Enough to redraw the marker, never enough to rebuild
   * the conversation: keep your own tombstone for that.
   */
  anchor?: CommentAnchor;
}
